modLoader="javafml"
loaderVersion="[46,)"

license="BSD-3-Clause"
issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
showAsResourcePack=false

[[mods]]
modId="create_new_age"
version="${version}"
displayName="Create: New Age"
logoFile="assets/create_new_age/icon.png"
authors="Antarctic Gardens"
description="An addon for the Create mod that adds integration with electricity"
displayTest="MATCH_VERSION"
displayURL="http://antarcticgardens.org/"

[[dependencies.create_new_age]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_new_age]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.create_new_age]]
modId="botarium"
mandatory=true
versionRange="[2.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_new_age]]
modId="create"
mandatory=true
versionRange="[0.5.1.d,)"
ordering="NONE"
side="BOTH"