modLoader="javafml"
loaderVersion="[43,)"

license="BSD-3-Clause"
issueTrackerURL="https://gitlab.com/antarcticgardens/create-new-age"
showAsResourcePack=false

[[mods]]
modId="create_new_age"
version="${version}"
displayName="Create: New Age"
logoFile="icon.png"
authors="Antarctic Gardens"
description="An addon for the Create mod that adds integration with electricity"
displayTest="MATCH_VERSION"
displayURL="http://antarcticgardens.org/"

[[dependencies.create_new_age]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_new_age]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"

[[dependencies.create_new_age]]
modId="botarium"
mandatory=true
versionRange="[1.8.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_new_age]]
modId="create"
mandatory=true
versionRange="[0.5.1.b,)"
ordering="NONE"
side="BOTH"